### ISSUE TITLE
Validation Error - /api/0.6/map Response misses description

### ISSUE THREAD

**Issue by commonism** [wtimme/osm-swagger#9]
Hi,

I noticed a validation error when using the description document:

```
aiopenapi3 validate _build/swagger.yaml 
ERROR:root:3 validation errors for Root
paths.paths.`/api/0.6/map`.get.responses.200.Response.description
  Field required [type=missing, input_value={'content': {'description...True, 'name': 'osm'}}}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
```

fix
```
diff --git a/_build/swagger.yaml b/_build/swagger.yaml
index 2b708bf..7805f5d 100644
--- a/_build/swagger.yaml
+++ b/_build/swagger.yaml
@@ -85,6 +85,7 @@ paths:
             - `top` is the latitude of the top (northernmost) side of the bounding box.
       responses:
         '200':
+          description: okay
           content:
             application/json:
               schema:
```

**Comment by wtimme** [comment]
Thanks for your contribution and your feedback, @commonism!

**Comment by commonism** [comment]
_build/swagger.yaml was not updated.

**Comment by wtimme** [comment]
Thanks for pointing that out! The bundled contract was not updated automatically. I have added a corresponding GitHub workflow to do that automatically.

**Comment by commonism** [comment]
Absolutely impressive job btw.

I was just wondering where the … interesting refs come from:
https://github.com/wtimme/openstreetmap-openapi/blob/3eaf6d9941dd9c72aa15eae206a5f8062b381dde/_build/swagger.yaml#L365-L366

swagger-cli bundle does this.

It may be valid though.

Interested in making it look nice?
Adding some intermediate schemas e.g. for Coordinate to reference to avoid referencing nested stacks.
swagger-ui will be nicer as well.

![image](https://github.com/wtimme/openstreetmap-openapi/assets/164513/ad07921d-7c99-46fa-9cf6-04c7da46207b)
